### ISSUE TITLE
Getting the following error when installing components

### ISSUE THREAD

**Issue by lgale05** [cgkineo/adapt-gulp-cli#2]
TypeError: First argument needs to be a number, array or string.
    at new Buffer (buffer.js:188:15)
    at Request.downloadHandler [as _callback](c:Userslaurie.galeAppDataRoam
ingnpmnode_modulesadapt-gulp-clinode_modulesgulp-downloadindex.js:37:57)
    at self.callback (c:\Users\laurie.gale\AppData\Roaming\npm\node_modules\adap
t-gulp-cli\node_modules\gulp-download\node_modules\request\request.js:360:22)
    at Request.EventEmitter.emit (events.js:95:17)
    at Request.onRequestError (c:\Users\laurie.gale\AppData\Roaming\npm\node_mod
ules\adapt-gulp-cli\node_modules\gulp-download\node_modules\request\request.js:1
008:8)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1547:9)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at Socket.onerror (tls.js:1445:17)
    at Socket.EventEmitter.emit (events.js:117:20)

**Comment by tomgreenfield** [comment]
@lgale05, could you detail the steps to produce this error please?

**Comment by tomgreenfield** [comment]
Closing this issue as v0.1.2 no longer utilises the gulp-download package.
